---
title: "aggregate_data_April13"
author: "Jenny Harris"
date: "4/23/2021"
output: html_document
---

```{r}
knitr::opts_chunk$set(echo = TRUE)

require(tidyverse)
require(ggplot2)
require(readxl)
require(REdaS) # for diagnostic data checks before FA
require(psych)# need for factor analysis
require(GPArotation) # need for factor analysis
require(polycor)
```

```{r}
#keeping the key 
ELAdata_touse_forFA_noNAs <- read.csv('ELAdata_with_subjectIDs.csv')
```


```{r}
###getting the correlation matrix of the data we currently have. This will allow us to determine whether certain variables are highly correlated with one another. NB. Had to remove demo_comb_income_v2 from p as too many categories
mix_corr_mat_preagg <-mixedCor(ELAdata_touse_forFA_noNAs[,c(2:77)], ncat = 6, smooth=TRUE,global=TRUE, correct=FALSE, c = c(5:12,14,72,74), p= c(13,22:31,67:71,73), d=c(1:4,15:21,32:66,75,76))
mix_corr_mat_preagg_df <- mix_corr_mat_preagg$rho
```

```{r}
write.csv(mix_corr_mat_preagg_df,file = "mixed_corr_matrix_preagg.csv", row.names = FALSE)
```

```{r}
cor.plot(mix_corr_mat_preagg_df)
```

```{r}
#####AGGREGATING THE VARIABLES THAT HAVE HIGH MULTICOLINEARITY BETWEEN ONE ANOTHER AND ALSO MAKE CONCEPTUAL SENSE TO GROUP TOGETHER. These are combining the initial individual variables (N.B. using dataframe not assigned as factors). If >2 variables are grouped the sum is halved to ensure that there are a maximum of 4 categories

##KSADS 758 -> 769 are highly correlated
ELAdata_touse_forFA_noNAs$ksads_ptsd_raw_758_759_760 <- ELAdata_touse_forFA_noNAs$ksads_ptsd_raw_758_p + ELAdata_touse_forFA_noNAs$ksads_ptsd_raw_759_p + ELAdata_touse_forFA_noNAs$ksads_ptsd_raw_760_p
ELAdata_touse_forFA_noNAs$ksads_ptsd_raw_758_759_760 <-ELAdata_touse_forFA_noNAs$ksads_ptsd_raw_758_759_760/2
ELAdata_touse_forFA_noNAs$ksads_ptsd_raw_758_759_760 <- ceiling(ELAdata_touse_forFA_noNAs$ksads_ptsd_raw_758_759_760)

ELAdata_touse_forFA_noNAs$ksads_ptsd_raw_761_to_765 <- ELAdata_touse_forFA_noNAs$ksads_ptsd_raw_761_p + ELAdata_touse_forFA_noNAs$ksads_ptsd_raw_762_p + ELAdata_touse_forFA_noNAs$ksads_ptsd_raw_763_p + ELAdata_touse_forFA_noNAs$ksads_ptsd_raw_764_p + ELAdata_touse_forFA_noNAs$ksads_ptsd_raw_765_p
ELAdata_touse_forFA_noNAs$ksads_ptsd_raw_761_to_765 <- ELAdata_touse_forFA_noNAs$ksads_ptsd_raw_761_to_765/2
ELAdata_touse_forFA_noNAs$ksads_ptsd_raw_761_to_765 <- ceiling(ELAdata_touse_forFA_noNAs$ksads_ptsd_raw_761_to_765)

ELAdata_touse_forFA_noNAs$ksads_ptsd_raw_767_768_769 <- ELAdata_touse_forFA_noNAs$ksads_ptsd_raw_767_p + ELAdata_touse_forFA_noNAs$ksads_ptsd_raw_768_p+ ELAdata_touse_forFA_noNAs$ksads_ptsd_raw_769_p
ELAdata_touse_forFA_noNAs$ksads_ptsd_raw_767_768_769 <-ELAdata_touse_forFA_noNAs$ksads_ptsd_raw_767_768_769/2
ELAdata_touse_forFA_noNAs$ksads_ptsd_raw_767_768_769 <- ceiling(ELAdata_touse_forFA_noNAs$ksads_ptsd_raw_767_768_769)

#demo_fam_exp1, _exp2 & _exp3, and _exp6 & _exp7 are highly correlated. Post aggregation exp1-3, 4 and 5 are all highly correlated
ELAdata_touse_forFA_noNAs$demo_fam_exp1_5_v2 <- ELAdata_touse_forFA_noNAs$demo_fam_exp1_v2 + ELAdata_touse_forFA_noNAs$demo_fam_exp2_v2 + ELAdata_touse_forFA_noNAs$demo_fam_exp3_v2 + ELAdata_touse_forFA_noNAs$demo_fam_exp4_v2 + ELAdata_touse_forFA_noNAs$demo_fam_exp5_v2
ELAdata_touse_forFA_noNAs$demo_fam_exp1_5_v2 <- ELAdata_touse_forFA_noNAs$demo_fam_exp1_5_v2/2
ELAdata_touse_forFA_noNAs$demo_fam_exp1_5_v2 <- ceiling(ELAdata_touse_forFA_noNAs$demo_fam_exp1_5_v2)

ELAdata_touse_forFA_noNAs$demo_fam_exp6_7_v2 <- ELAdata_touse_forFA_noNAs$demo_fam_exp6_v2 + ELAdata_touse_forFA_noNAs$demo_fam_exp7_v2

#post aggregation famhx_ss_moth_prob_alc_p and famhx_ss_moth_prob_dg_p are too highly correlated 
ELAdata_touse_forFA_noNAs$famhx_ss_moth_prob_alc_dg <-ELAdata_touse_forFA_noNAs$famhx_ss_moth_prob_alc_p +ELAdata_touse_forFA_noNAs$famhx_ss_moth_prob_dg_p
```


```{r}
####REMOVING THE ORIGINAL VARIABLES WE AGGREGATED (plus asr_scr variables that are also covered in other variables)

ELAdata_touse_forFA_noNAs_noOriginalVar <- ELAdata_touse_forFA_noNAs %>% 
    dplyr::select(-ksads_ptsd_raw_758_p, -ksads_ptsd_raw_759_p, -ksads_ptsd_raw_760_p,
           -ksads_ptsd_raw_761_p, -ksads_ptsd_raw_762_p, -ksads_ptsd_raw_763_p,
           -ksads_ptsd_raw_764_p, -ksads_ptsd_raw_765_p, -ksads_ptsd_raw_767_p, 
           -ksads_ptsd_raw_768_p, -ksads_ptsd_raw_769_p,
           -demo_fam_exp1_v2, -demo_fam_exp2_v2, -demo_fam_exp3_v2,  
           -demo_fam_exp4_v2, -demo_fam_exp5_v2,
           -demo_fam_exp6_v2, -demo_fam_exp7_v2,
           -asr_scr_inattention_r, -asr_scr_hyperactive_r,
           -famhx_ss_moth_prob_dg_p,-famhx_ss_moth_prob_alc_p)

```


```{r}
####CHECKING FREQUENCIES POST AGGREGATION - will remove variables with an incidence rate <0.05% 
IncidenceRates_Zero_ELA <- apply(ELAdata_touse_forFA_noNAs_noOriginalVar, 2, function(x) sum(x == 0))
IncidenceProportion_Zero_ELA <- as.data.frame(IncidenceRates_Zero_ELA/nrow(ELAdata_touse_forFA_noNAs_noOriginalVar))

IncidenceProportion_Zero_ELA_filter <- filter(IncidenceProportion_Zero_ELA, IncidenceRates_Zero_ELA/nrow(ELAdata_touse_forFA_noNAs_noOriginalVar) > .995)
##I think we could have a quick summary here as to whether we removed any variables based on this criteria. What do you think? - Hajer 
```


```{r}
###getting the correlation matrix of the data post-aggregation. NB. Had to remove demo_comb_income_v2 from p as too many categories
mix_corr_mat_postagg <-mixedCor(ELAdata_touse_forFA_noNAs_noOriginalVar[,c(2:61)], ncat = 6, smooth=TRUE,global=TRUE, correct=FALSE, c = c(3:8,10,50,52), p= c(9,11:20,45:49,51,55:60), d=c(1:2,21:44,53,54))
mix_corr_mat_postagg_df <- mix_corr_mat_postagg$rho
```

```{r}
write.csv(mix_corr_mat_postagg_df,file = "mixed_corr_matrix_postagg.csv", row.names = FALSE)

```


```{r}
cor.plot(mix_corr_mat_postagg_df)
```

```{r}
###writing this dataframe 
write.csv(ELAdata_touse_forFA_noNAs_noOriginalVar, file = "ELAdata_touse_forFA_noNAs_noOriginalVar.csv", row.names=FALSE)
```

#site analysis

```{r}
#read in site
site <- read_tsv(paste('abcd_lt01.txt', sep='/'), col_names=TRUE) %>%
  filter(eventname == "baseline_year_1_arm_1") %>% 
  dplyr::select(subjectkey,site_id_l)

ELAdata_touse_forFA_noNAs_noOriginalVar_site <- ELAdata_touse_forFA_noNAs_noOriginalVar %>%
    left_join(site,by='subjectkey')%>%
    dplyr::rename(abcd_site = 'site_id_l')
head(ELAdata_touse_forFA_noNAs_noOriginalVar_site)

ELAdata_touse_forFA_noNAs_noOriginalVar_site$abcd_site <- as.factor(ELAdata_touse_forFA_noNAs_noOriginalVar_site$abcd_site)
```

```{r}
#Split file according to site
NoSite01 <- subset(ELAdata_touse_forFA_noNAs_noOriginalVar_site, abcd_site!="site01")
NoSite02 <- subset(ELAdata_touse_forFA_noNAs_noOriginalVar_site, abcd_site!="site02")
NoSite03 <- subset(ELAdata_touse_forFA_noNAs_noOriginalVar_site, abcd_site!="site03")
NoSite04 <- subset(ELAdata_touse_forFA_noNAs_noOriginalVar_site, abcd_site!="site04")
NoSite05 <- subset(ELAdata_touse_forFA_noNAs_noOriginalVar_site, abcd_site!="site05")
NoSite06 <- subset(ELAdata_touse_forFA_noNAs_noOriginalVar_site, abcd_site!="site06")
NoSite07 <- subset(ELAdata_touse_forFA_noNAs_noOriginalVar_site, abcd_site!="site07")
NoSite08 <- subset(ELAdata_touse_forFA_noNAs_noOriginalVar_site, abcd_site!="site08")
NoSite09 <- subset(ELAdata_touse_forFA_noNAs_noOriginalVar_site, abcd_site!="site09")
NoSite10 <- subset(ELAdata_touse_forFA_noNAs_noOriginalVar_site, abcd_site!="site10")
NoSite11 <- subset(ELAdata_touse_forFA_noNAs_noOriginalVar_site, abcd_site!="site11")
NoSite12 <- subset(ELAdata_touse_forFA_noNAs_noOriginalVar_site, abcd_site!="site12")
NoSite13 <- subset(ELAdata_touse_forFA_noNAs_noOriginalVar_site, abcd_site!="site13")
NoSite14 <- subset(ELAdata_touse_forFA_noNAs_noOriginalVar_site, abcd_site!="site14")
NoSite15 <- subset(ELAdata_touse_forFA_noNAs_noOriginalVar_site, abcd_site!="site15")
NoSite16 <- subset(ELAdata_touse_forFA_noNAs_noOriginalVar_site, abcd_site!="site16")
NoSite17 <- subset(ELAdata_touse_forFA_noNAs_noOriginalVar_site, abcd_site!="site17")
NoSite18 <- subset(ELAdata_touse_forFA_noNAs_noOriginalVar_site, abcd_site!="site18")
NoSite19 <- subset(ELAdata_touse_forFA_noNAs_noOriginalVar_site, abcd_site!="site19")
NoSite20 <- subset(ELAdata_touse_forFA_noNAs_noOriginalVar_site, abcd_site!="site20")
NoSite21 <- subset(ELAdata_touse_forFA_noNAs_noOriginalVar_site, abcd_site!="site21")
NoSite22 <- subset(ELAdata_touse_forFA_noNAs_noOriginalVar_site, abcd_site!="site22")
```

```{r}
#Remove abcd_site variable
NoSite01 <- NoSite01 %>% 
  dplyr::select(-abcd_site)
NoSite02 <- NoSite02 %>% 
  dplyr::select(-abcd_site)
NoSite03 <- NoSite03 %>% 
  dplyr::select(-abcd_site)
NoSite04 <- NoSite04 %>% 
  dplyr::select(-abcd_site)
NoSite05 <- NoSite05 %>% 
  dplyr::select(-abcd_site)
NoSite06 <- NoSite06 %>% 
  dplyr::select(-abcd_site)
NoSite07 <- NoSite07 %>% 
  dplyr::select(-abcd_site)
NoSite08 <- NoSite08 %>% 
 dplyr:: select(-abcd_site)
NoSite09 <- NoSite09 %>% 
  dplyr::select(-abcd_site)
NoSite10 <- NoSite10 %>% 
 dplyr:: select(-abcd_site)
NoSite11 <- NoSite11 %>% 
 dplyr:: select(-abcd_site)
NoSite12 <- NoSite12 %>% 
  dplyr::select(-abcd_site)
NoSite13 <- NoSite13 %>% 
  dplyr::select(-abcd_site)
NoSite14 <- NoSite14 %>% 
  dplyr::select(-abcd_site)
NoSite15 <- NoSite15 %>% 
  dplyr::select(-abcd_site)
NoSite16 <- NoSite16 %>% 
  dplyr::select(-abcd_site)
NoSite17 <- NoSite17 %>% 
  dplyr::select(-abcd_site)
NoSite18 <- NoSite18 %>% 
  dplyr::select(-abcd_site)
NoSite19 <- NoSite19 %>% 
  dplyr::select(-abcd_site)
NoSite20 <- NoSite20 %>% 
  dplyr::select(-abcd_site)
NoSite21 <- NoSite21 %>% 
  dplyr::select(-abcd_site)
NoSite22 <- NoSite22 %>% 
  dplyr::select(-abcd_site)
```

```{r}
###writing tese dataframes
write.csv(NoSite01, file = "NoSite01.csv", row.names=FALSE)
write.csv(NoSite02, file = "NoSite02.csv", row.names=FALSE)
write.csv(NoSite03, file = "NoSite03.csv", row.names=FALSE)
write.csv(NoSite04, file = "NoSite04.csv", row.names=FALSE)
write.csv(NoSite05, file = "NoSite05.csv", row.names=FALSE)
write.csv(NoSite06, file = "NoSite06.csv", row.names=FALSE)
write.csv(NoSite07, file = "NoSite07.csv", row.names=FALSE)
write.csv(NoSite08, file = "NoSite08.csv", row.names=FALSE)
write.csv(NoSite09, file = "NoSite09.csv", row.names=FALSE)
write.csv(NoSite10, file = "NoSite10.csv", row.names=FALSE)
write.csv(NoSite11, file = "NoSite11.csv", row.names=FALSE)
write.csv(NoSite12, file = "NoSite12.csv", row.names=FALSE)
write.csv(NoSite13, file = "NoSite13.csv", row.names=FALSE)
write.csv(NoSite14, file = "NoSite14.csv", row.names=FALSE)
write.csv(NoSite15, file = "NoSite15.csv", row.names=FALSE)
write.csv(NoSite16, file = "NoSite16.csv", row.names=FALSE)
write.csv(NoSite17, file = "NoSite17.csv", row.names=FALSE)
write.csv(NoSite18, file = "NoSite18.csv", row.names=FALSE)
write.csv(NoSite19, file = "NoSite19.csv", row.names=FALSE)
write.csv(NoSite20, file = "NoSite20.csv", row.names=FALSE)
write.csv(NoSite21, file = "NoSite21.csv", row.names=FALSE)
write.csv(NoSite22, file = "NoSite22.csv", row.names=FALSE)
```
