---
title: "01_parallel_FA_ELA_April13"
author: "Jenny Harris"
date: "4/23/2021"
output: html_document
---


```{r}
knitr::opts_chunk$set(echo = TRUE)

require(tidyverse)
require(ggplot2)
require(readxl)
require(REdaS) # for diagnostic data checks before FA
require(psych)# need for factor analysis
require(GPArotation) # need for factor analysis
library(corpcor) # need for factor analysis
require(polycor)
```

### Load in data

```{r}
Final_ELAData <- read.csv('ELAdata_touse_forFA_noNAs_noOriginalVar.csv')

#remove IDs for matrix
Final_ELAData_noIDs <- Final_ELAData %>% 
    dplyr::select(-subjectkey)
```


### Create correlation matrix
```{r}
###Getting correlation matrix for parallel analysis NB. Had to remove demo_comb_income_v2 from p as too many categories
mix_corr_mat_final <-mixedCor(Final_ELAData_noIDs, ncat = 6, smooth=TRUE,global=TRUE, correct=FALSE, c = c(3:8,10,50,52), p= c(9,11:20,45:49,51,55:60), d=c(1:2,21:44,53,54))
mix_corr_mat_final_df <- mix_corr_mat_final$rho
cor.plot(mix_corr_mat_final_df)
```

```{r}
# parallel analysis 
#fa.parallel The parallel factors technique compares the observed eigenvalues of a correlation
#relation matrix with those from random data.

# iterations increased to get a more stable estimate! 
par_analysis <- fa.parallel(mix_corr_mat_final_df, n.obs = nrow(Final_ELAData_noIDs), n.iter = 1000, error.bars = TRUE)
```

```{r}

par_analysis

#Eigen values of factors shows 7 factors with eigen values >1
```


```{r}
save(par_analysis, file = "parallel_analysis_results.Rdata")
```

